### ISSUE TITLE
Ajustes en Resoluciones bajas ( < 700px ancho)

### ISSUE THREAD

**Issue by drzippie** [SevillaDevelopers/sevilladevelopers.github.io#19]
El titulo se pierde
![sevilla_developers_user_group](https://cloud.githubusercontent.com/assets/239421/25101668/66394f18-23b5-11e7-9d2f-397edfd3e4ff.jpg)

La dirección del calendario provoca que toda la web no ajuste el ancho correctamente y se muestren scrolls horizontales
![sevilla_developers_user_group](https://cloud.githubusercontent.com/assets/239421/25101718/9381bbf4-23b5-11e7-8707-34540e7f29da.jpg)

El texto del pie no se lee (alto de línea)
![sevilla_developers_user_group](https://cloud.githubusercontent.com/assets/239421/25101763/d225ac44-23b5-11e7-873d-edf818531965.jpg)

**Comment by drzippie** [comment]
Pull Request: #20

**Comment by israbr** [comment]
Pull Request: #20
