### ISSUE TITLE
Listado de sitios públicos en Sevilla donde sentarse a gusto a trabajar

### ISSUE THREAD

**Issue by danibishop** [SevillaDevelopers/sevilladevelopers.github.io#25]
Inspirado por [esto](https://www.facebook.com/groups/sevilladevelopers/permalink/1858919294178397/).

La cosa es poner una tablita con los sitios, link a Google Maps y un par de columnas diciendo si hay WiFi, café y eso.

**Comment by miguelbemartin** [comment]
Buena idea!

**Comment by israbr** [comment]
Ole!
@danibishop pa cuando ese PR ;-)

**Comment by danibishop** [comment]
He abierto el ticket para recordármelo, mpadre.

**Comment by danibishop** [comment]
He abierto el ticket para recordármelo!
