### ISSUE TITLE
Texto apenas visible en el frontal

### ISSUE THREAD

**Issue by jessanmen1** [SevillaDevelopers/sevilladevelopers.github.io#9]
El otro día accedí al portal desde otro pc con un shitty monitor y no le di importancia, pero cuando he accedido desde casa sigo viéndolo fatal, algo borroso. ¿Es mi culpa? Yo lo veo tal que así: (Google Chrome Versión 57.0.2987.133 (64-bit))

![image](https://cloud.githubusercontent.com/assets/6974499/24951540/0d10f588-1f75-11e7-9daf-9bd5d0ac1e9c.png)

Haciendo una prueba rápida cambiando el CSS (de hecho, quitando el font-weight lo veo muchísimo mejor)

![image](https://cloud.githubusercontent.com/assets/6974499/24951729/b69aacd4-1f75-11e7-832b-56f950c8005f.png)

Sentíos libres de cerrar el issue si soy al único al que le ocurre esto.

**Comment by pitbulk** [comment]
Yo he experimentado lo mismo, apenas se ve...

**Comment by miguelbemartin** [comment]
Creo que es porque no estaba añadida la fuente correctamente y además quizás al tenerla añadida directamente a mi equipo yo no había experimentado eso. Enviado nuevo Pullrequest.

**Comment by israbr** [comment]
Aqui teneis el resultado https://miguelbemartin.github.io/sevilladevelopers.github.io/
echadle un ojo los que no lo veis y nos decis si aprovamos el cambio or not
